encryptionsalt: v1:QiUd4qNAqng=:v1:tCt5J/nnMKCFE8a0:YRjy4AlM+iMG9p2i6p+INBIec3K14Q==
config:
  aws:region: eu-central-1
  hlidacshopu:screenshotter-host:
    secure: v1:iXpR/kcnoIBWraUv:XR8WLNcN80Bwipg89FFXfVBUxrLQ96HeanfZ64YFupoiaOFDe2RKumO6535B8jHDe2zg/A==
  hlidacshopu:screenshotter-token:
    secure: v1:ybTev0xd+QNaEjXX:oan26gwsm19BmBZEh3XIDAwehETuZSOAiPVGLwJCECtWNthO4se9soY=
  hlidacshopu:data_bucket: data.hlidacshopu.cz
  topmonks_website:assets_paths:
    - /assets/*
  hlidac-shopu:screenshotter-host:
    secure: v1:Z++VTw7xFN07E74K:Dz1072o4bG3GblpXa1PY2C2hi2LvrhK65l+g7UrdF+r0Rbge/kLAsK5wrWATSfHPypZTHqkI/TFtF35WXw==
  hlidac-shopu:screenshotter-token:
    secure: v1:yEeeYA2ihEGW1x5g:sMMg9yTb1XX7Z/rIsLZttc56o697kg9/iNAik3IlDIhf+Zv95bKsEhPugYFmpQL8HSMZpw/hG2ICs4UCFp3TmEF7
